// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export type {
  // server loader
  IServerLoaderArgs,
  UmiRequest,
  ServerLoader,
  // metadata loader
  MetadataLoader,
  IMetadata,
  IMetaTag,
} from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/@umijs+server@4.4.9/node_modules/@umijs/server/dist/types'
