// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/@umijs+renderer-react@4.4.9_8637724ac9176005f5615186b7ccc823/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/@umijs+renderer-react@4.4.9_8637724ac9176005f5615186b7ccc823/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/umi@4.4.9_@babel+core@7.26._26c832669c15d6d605dac1c86f58f1c8/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
