// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { QueryClientConfig } from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/@tanstack+react-query@4.36._0f261c9fbe22bd62978d878f4b0f9d5d/node_modules/@tanstack/react-query';

import { ReactQueryDevtools } from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/@tanstack+react-query-devto_7093df4b8f8e71d99b893f56732cddac/node_modules/@tanstack/react-query-devtools';


export type RuntimeReactQueryType = {
  
  devtool?: React.ComponentProps<typeof ReactQueryDevtools>

  queryClient?: QueryClientConfig
}
