// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProfileOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CheckCircleOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from '/mnt/c/Users/bmarl/OneDrive/Documents/Apps/cauldronos/app/myapp/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, ProfileOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined };
