// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","parentId":"1","id":"2"},"3":{"path":"/users","access":"canManageUsers","parentId":"1","id":"3"},"4":{"path":"/settings","access":"canManageSettings","parentId":"1","id":"4"},"5":{"path":"/ai","access":"canAccessAI","parentId":"1","id":"5"},"6":{"path":"/modules","access":"canManageModules","parentId":"1","id":"6"},"7":{"path":"*","parentId":"1","id":"7"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__MainLayout" */'@/layouts/MainLayout.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__dashboard__index" */'@/pages/dashboard/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__users__index" */'@/pages/users/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__settings__index" */'@/pages/settings/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__ai__index" */'@/pages/ai/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__modules__index" */'@/pages/modules/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
},
  };
}
