// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  QueryClient,
  QueryCache,
  MutationCache,
  QueryObserver,
  InfiniteQueryObserver,
  QueriesObserver,
  MutationObserver,
  useQuery,
  useQueries,
  useInfiniteQuery,
  useMutation,
  useIsFetching,
  useIsMutating,
  QueryClientProvider,
  useQueryClient,
  QueryErrorResetBoundary,
  useQueryErrorResetBoundary,
  useIsRestoring,
  IsRestoringProvider
} from 'C:/Users/DevToolsUser/cauldronos/node_modules/.pnpm/@tanstack+react-query@4.36._0f261c9fbe22bd62978d878f4b0f9d5d/node_modules/@tanstack/react-query';
